name: CI/CD Pipeline for Todo List App

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker environment
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/todo-list-app || exit 1
            echo "Pulling latest changes from GitHub..."
            git reset --hard
            git pull origin main || exit 1

            echo "Stopping existing Docker containers..."
            docker-compose down || echo "No containers to stop."

            echo "Building and starting Docker containers..."
            docker-compose up --build -d || exit 1

            echo "Deployment completed successfully!"
          EOF
